language: python
python:
  - 2.7
  - 3

install:
  - pip install tox coveralls

script:
  - tox

after_success:
  - coveralls

sudo: required

dist: trusty

env:
  matrix:
    - TOXENV=pylama
    - TOXENV=pypy-coverage
    - TOXENV=py27-coverage
    - TOXENV=p3-coverage
