language: python

install:
  - pip install tox coveralls

script:
  - tox

sudo: true

after_success:
  - coveralls

env:
  - TOXENV=pylama
  - TOXENV=pypy-coverage
  - TOXENV=py27-coverage
  - TOXENV=p34-coverage
  - TOXENV=p35-coverage
